[package]
name = "persistent_store"
version = "0.1.0"
authors = ["Julien Cretin <cretin@google.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
libtock_platform = { path = "../../third_party/libtock-rs/platform" }

[dev-dependencies]
tempfile = "3"

[features]
std = []
